### ISSUE TITLE
Bug?  (disappearing buttons on Big Sur)

### ISSUE THREAD

**Issue by DevulderJeanPaul** [dagronf/DSFStepperView#1]
Hi,
On example
when I click on "+" or "-" button, when I release the mouse bouton
the nsbutton disappears!!

**Comment by dagronf** [comment]
Ah that’s interesting!  I’ve been mostly testing on 10.15 and haven’t seen anything like this, which OS version are you using?

**Comment by DevulderJeanPaul** [comment]
hi,
Big Sur 11.0.1

**Comment by dagronf** [comment]
Ah. I haven't tested it on a recent Big Sur (I'm running it in VMs) - I'll upgrade to the latest and try again.

Which Xcode version are you using?

**Comment by DevulderJeanPaul** [comment]
Version 12.2 beta 4 (12B5044c)

**Comment by dagronf** [comment]
Hey mate - I was able to reproduce (and fix) the issue on Big Sur -- looks like Big Sur has changed the button behaviour if you don't explicitly set its type (my mistake!)

If you try version 1.0.1 which should be available now and verify that'd be great.

**Comment by DevulderJeanPaul** [comment]
great it's fixed!
thanks,

**Comment by dagronf** [comment]
Good to hear!  Thanks for the help mate.
