### ISSUE TITLE
DSFStepperView-shared linker issue for iOS Device build

### ISSUE THREAD

**Issue by amagrude** [dagronf/DSFStepperView#5]
When I added this to an existing project via SPM, I was unable to get it to build to run on a device, but it ran just fine in the simulator. I received this error:

No such file or directory: '/Users/andrewmagruder/Library/Developer/Xcode/DerivedData/Multi-Tool-eltmjcbmaxjdygagnsgbmawozdfs/Build/Products/Debug-iphoneos/PackageFrameworks/DSFStepperView-shared.framework/DSFStepperView-shared'

To correct this, I went Target->Frameworks, Libraries, and Embedded Content->DSFStepperView-shared->Filters->Unchecked "Allow on any platform" && "iOS".

This cleared my linker error and now the app builds/runs on device and in simulator.

Xxode: 15.2. iOS: 17.2. Device: iPhone 14 Pro Max.

Works great! Thank you! 👍

**Comment by dagronf** [comment]
Glad you were able to resolve your issue. As much as Apple states 'just add it! It's simple!' sometimes its far from the truth.

This library has three targets

* DSFStepperView: Let SwiftPM decide how to integrate the library
* DSFStepperView-static: Build the library as a static library
* DSFStepperView-shared: Build the library as a shared library

In most cases you only ever need to use the first one. I had a number of requests for specific shared/static targets for people that want fine control over how their app is built (which unfortunately makes the initial integration a little more confusing).

Cheers!

**Comment by TheMartas29** [comment]
As mentioned above. Its totally fine to import jus the "DSFStepperView" and ignore the other two, when importing via SPM :)
